version: "3.7"
networks:
  default:
    name: test-net

x-common: &common
  restart: always

services:
  database:
    <<: *common
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    # volumes:
    #   - data:/var/lib/postgresql/data
  pgadmin:
    <<: *common
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    ports:
      - "5431:80"
# volumes:
#   data:
