version: "3.7"
networks:
  default:
    name: test-net

x-common: &common
  image: dgraph/dgraph:v20.07.2
  restart: always
  # volumes:
  #   - data:/dgraph

services:
  zero:
    <<: *common
    command: dgraph zero --my=zero:5080
  alpha:
    <<: *common
    ports:
      - 8081:8080
      - ${PORT}:9080
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --whitelist 172.1.0.0:172.30.0.0
  ratel:
    <<: *common
    ports:
      - 8001:8000
    command: dgraph-ratel
# volumes:
#   data:
